puppetlabs/puppetlabs-concat

- manifests/setup.pp
AIX find does not support the print0 option. It's basically the same as on Solaris:
Debug: Executing '/var/lib/puppet/concat/bin/concatfragments.sh -o "/var/lib/puppet/concat/_var_ossec_etc_ossec-agent.conf/fragments.concat.out" -d "/var/lib/puppet/concat/_var_ossec_etc_ossec-agent.conf" -t'
Debug: /Stage[main]/Ossec::Client/Concat[/var/ossec/etc/ossec-agent.conf]/Exec[concat_/var/ossec/etc/ossec-agent.conf]/unless: find: bad option -print0
> use concatfragments.rb on AIX

- manifests/init.pp
- spec/unit/classes/concat_setup_spec.rb
- spec/unit/defines/concat_fragment_spec.rb
- spec/unit/defines/concat_spec.rb
Ruby is not in the path for all PE installations, so make sure the
concat script is run with ruby in the path.
> MODULES-1456 - make sure ruby is in path on PE

- README.md
- manifests/init.pp
- spec/acceptance/validation_spec.rb
- spec/unit/defines/concat_spec.rb
This patch allows a user to pass an optional `validate_cmd` parameter to a `concat` resource, which in turn will run a command to validate the output of the file before the module replaces it. It follows the same semantics as the `validate_cmd` parameter to the `file` resource.
Example:
```puppet
concat { '/etc/httpd/conf/httpd.conf':
ensure       => file,
validate_cmd => '/usr/sbin/apache2 -t -f %',
owner        => 'apache2',
group        => 'apache2',
mode         => '0644'
}
```
> Support running a validation command on the destination file.

- README.md
- manifests/init.pp
The validate_cmd parameter is only valid on newer versions of puppet.
This module is supporting all 3.x versions of puppet. This commit only
applies the validate_cmd parameter to the file resource if it is
defined and adds documentation noting that it will not work on older
versons of puppet.
> Fix validate_cmd file resource parameter

- manifests/init.pp
If the system is not running PE, the $::is_pe fact will be undefined,
causing errors when run under strict variables mode. This patch uses
the getvar() function to look up the fact so that it won't fail if not
defined.
Alternative to https://github.com/puppetlabs/puppetlabs-concat/pull/270
This should fix the broken CI for the postgresql module.
> Lookup is_pe fact with getvar

- manifests/init.pp
Reverts puppetlabs/puppetlabs-concat#273
Using defined() as in #270 is preferred in order to be compatible with the future parser.
> Revert "Lookup is_pe fact with getvar"

- manifests/init.pp
$is_pe is not a standard fact, so the
current code fails with strict_variables on.
> Check if $is_pe exists before using it

- manifests/fragment.pp
- spec/unit/defines/concat_fragment_spec.rb
Per discussion on #272, we're going to validate $order rather than worry
about needing to make substitutions on it.
> Add validation for order parameter

- manifests/fragment.pp
- manifests/setup.pp
- spec/unit/defines/concat_fragment_spec.rb
gid has now been part of facter for a long time, it is safe to use
it now.
> set group of fragments to gid

- manifests/fragment.pp
When testing the order parameter on sanity, make sure that
pattern matching is only exercised on strings. Integers
don't like that.
Without the patch, and integer passed, you end up with below error and aborted catalog like this:
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Left match operand must result in a String value. Got an Integer. at /etc/puppet/environments/production/modules/concat/manifests/fragment.pp:45:11 on node XXX
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
> Fixup $order parameter verification

- manifests/setup.pp
When files on a puppetmaster are owned by a non-root user,
concatfragments.sh gets installed on the nodes with a group
owner matching the one of the master.
This has no security implications since the file is mode 755,
but does lead to possible ping-pong situations when switching
between environments where the files on the master have
different group ownership.
Use '0' instead of 'root', since the root user's main group
isn't always 'root' on some BSDs, but always '0'.
> Set script's group to 0 if script owner is root

- manifests/setup.pp
- spec/unit/classes/concat_setup_spec.rb
Hi,
I think user and group properties need to be set explicitly for the concat *runtime environment* (base dir and script).
As Puppet propagates resources defaults to included modules, declaring something like
```puppet
File {
owner => bind,
group => root
}
```
in a module makes concat create its basedir belonging to user `bind`.
Jérôme
> setup: set user/group explicitly for dirs & script

- manifests/setup.pp
Broken since the switch from the shell script to the ruby script.
I did something stupid with git while trying to rebase, this is the same as what I had in #276, fixing the breakage introduced with the switch from concatfragments.sh to concatfragments.rb
> Fix breakage on OpenBSD in similar fashion as it is done for Windows.

- manifests/fragment.pp
- manifests/init.pp
Commit: 6cfa62bce433f44c4ea6279adcb886e038e44df1 
Issue: #296 
seems to have broken regex on Linux (Ubuntu 14.04, Puppet 3.7.5):
Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, regsubst(): Bad regular expression `[/:\n\s\\]' at /etc/puppet/environments/development/modules/concat/manifests/init.pp:77:27
Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, regsubst(): Bad regular expression `[/:\n\s\\]' at /etc/puppet/environments/development/modules/concat/manifests/fragment.pp:47:23
> Revert and fix regex

- metadata.json
Previously there was a trailing comma after the last item in a list.
That is invalid in JSON. This commit removes that one comma.
> (maint) fixup invalid JSON

- README.md
- lib/puppet/type/concat_fragment.rb
- manifests/fragment.pp
- manifests/init.pp
- spec/acceptance/warnings_spec.rb
Needed to bind fragment targets to it's parent concat resource's title so that we can
find them in the catalog. Throws a warning if the target is not found.
> fix fragment target handling

- README.md
- manifests/init.pp
Before 2.0.0, this parameter would add a newline at the end of the warn
message. To improve flexibilty, this was removed. Please add it
explicitely if you need it.
> (MODULES-2080) Call out changed behaviour of 'warn' parameter

- lib/puppet/type/concat_file.rb
autorequire will add parent directories of the concat_file to the dependency chain.
So they can be created in the right order if they do not exist.
> adds file autorequire

- lib/puppet/type/concat_file.rb
With Concat 2.0.x we've deprecated the -force parameter and the resulting bug
caused concat files that have no content/fragments to overwrite the target file with an
empty file. Concat should only create an empty file if no file exists, and if the file
exists, then it should not overwrite it with an empty file.
> fix defaulted force behavior

- lib/puppet/type/concat_file.rb
concat_file generates a file resource which will manage the content,
while the interface for requirements is Concat[] or at least
Concat_file[]. The file is currently flowing within the graph
without any dependency. However, so that require and notifies are
working properly, the file must be present before the concat_file
resource is finished being managed and potentially other resources
depending on that one are being managed.
This also makes the copy & paste from looking for the parent
directory as originaly described within MODULES-2023 obsolete, as
this will be handled by the file itself.
> (MODULES-2023) - autorequire the file we are generating

- manifests/init.pp
stdlib now provides an $::is_pe fact, which defaults to "false".
When compared as a string, it is evaluated to true.
This is https://github.com/puppetlabs/puppetlabs-concat/pull/336 rebased on `master`
> Compare $::is_pe as bool, not string

- README.md
- metadata.json
Fairly self-explanatory. This simply adds Solaris 12 to metadata.json.
> Add support for Solaris 12

- manifests/setup.pp
On FreeBSD systems, the Ruby interpreter is normally installed in
/usr/local/bin, which is not on the default PATH when running init
scripts.  Most users will have it in their PATH when logged in, which
causes concat to fail when run from init (or "service puppet start")
but not when run from directly the command line ("sudo puppet agent").
This follows the same strategy as OpenBSD, but avoid specifying the
Ruby interpreter version explicitly, because FreeBSD supports three
different versions of Ruby (with the default always being installed as
/usr/local/bin/ruby).
> (#2208) FreeBSD: call /usr/local/bin/ruby explicitly

- manifests/fragment.pp
- manifests/init.pp
- spec/unit/defines/concat_fragment_spec.rb
- spec/unit/defines/concat_spec.rb
The backup option, provided to the `concat` resource is used to backup the final target file before overwritting it.
Problem is: the backup option is used for the concat fragments file resources and, even worse, the fragments directory.
It means that, when `backup` is enabled (say ".bak") and a fragment changes, the file is first backed up inside the fragment dir, then removed (directory has purge, recurse set to true), but backed up again because the `File[/var/lib/puppet/concat/_target_file]` also has `backup => ".bak"` !
**The final concatenated file results in the fragment appearing twice !**
Pull request fixes this issue.
I've been able to update unit test, but I can't run the acceptance ones. Maybe they need to be updated as well.
Please consider this before the 1.2.4 release, I …
> Backup option breaks concat

- manifests/setup.pp
is also used by Puppet, so adapt to that.
Tested on OpenBSD 5.8-beta, and 5.7-snapshot.
Using ::kernelversion instead of ::operatingsystemrelease, because
::operatingsystemrelease can be 5.7, 5.8, 5.7-snapshot, 5.8-beta etc.
Note that it was myself that introduced the /usr/local/bin/ruby21 interpreter in the module here with OpenBSD 5.7 a few month ago. Since it's there untouched, I doubt anyone is using it with older versions of OpenBSD, and therefore I don't think its worth caring about them.
Let me know if I can change/enhance anything, otherwise, pleae consider for merge.
cheers,
Sebastian
> Recent OpenBSD changed to ruby22 as default interpreter, that now

- manifests/init.pp
- spec/unit/defines/concat_spec.rb
This allows specifying a numerical user ID or group ID for the $owner
and $group parameters, respectively. Currently, only string values for
the user name and group name are allowed, but these parameters are
passed straight to the file resource that is created, which supports
both string name and numeric ID.
> Allow integer UID/GID for $owner/$group

- spec/acceptance/nodesets/centos-59-x64.yml
- spec/acceptance/nodesets/centos-64-x64-pe.yml
- spec/acceptance/nodesets/centos-64-x64.yml
- spec/acceptance/nodesets/centos-65-x64.yml
- spec/acceptance/nodesets/debian-607-x64.yml
- spec/acceptance/nodesets/debian-70rc1-x64.yml
- spec/acceptance/nodesets/debian-73-x64.yml
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/fedora-18-x64.yml
- spec/acceptance/nodesets/sles-11-x64.yml
- spec/acceptance/nodesets/sles-11sp1-x64.yml
- spec/acceptance/nodesets/ubuntu-server-10044-x64.yml
- spec/acceptance/nodesets/ubuntu-server-12042-x64.yml
The vagrant boxes at puppet-vagrant-boxes.puppetlabs.com were removed a
few months ago in favor of those hosted at atlas.hashicorp.com. This
switches the acceptance test nodesets to specify the correct URL which
makes it possible to manually run the acceptance tests.
> (MODULES-2572) Fix acceptance test vagrant URLs

- lib/puppet/type/concat_file.rb
Need to use :path instead of :name, as path is the namevar of the File resource.
> fixes resource reference in concat_file eval_generate return

- .gitattributes
7eb14b77 removed files/concatfragments.sh and used concatfragments.rb instead. #80 fixed the issue i have for the former .sh file, this PR fixes it for the new .rb file.
actually, this changes the line endings for all .rb files. i don't know whether that's the right way to go...
> Fix line endings on windows

- README.md
- manifests/fragment.pp
- manifests/init.pp
- spec/unit/defines/concat_fragment_spec.rb
- spec/unit/defines/concat_spec.rb
- tests/fragment.pp
- tests/init.pp
Add show_diff to concat and concat::fragment types.
> MODULES-1678 - Add show_diff attribute to concat and concat::fragment defined types

- spec/spec_helper_acceptance.rb
The shell() command runs the command on the default host, and beaker now
fails on this.
> Fix helper on host command

- metadata.json
https://github.com/puppetlabs/puppetlabs-concat/commit/f4241b5ffea66e69d9c51fa3ae327fdcd379013f referenced is_bool() from stdlib that was only added in 4.2.0, according to: https://github.com/puppetlabs/puppetlabs-stdlib/blob/04fa5a0cd9255dc2d51af517be7164db9ea0306b/CHANGELOG.md
> Fix the minimum required stdlib version to 4.2.0.

- lib/puppet/type/concat_file.rb
This is a fix for the fix provided in #391, which was still not working correctly for alpha sorting.
When given an array of fragments that results in:
`["1__string1", "2__string2", "10__string10"]`
The correct alpha ordering/sorting should be:
`["1__string1", "10__string10", "2__string2"]`
The previous fix in PR #391 resulted in:
`["10__string10", "1__string1", "2__string2"]`
> (MODULES-3097) Re-fix fragment sorting by alpha

- lib/puppet/type/concat_file.rb
At the moment `validate_cmd` does nothing because it isn't propagated to the `file` resource.
> MODULES-3156: propagate the validate_cmd to the file resource

- manifests/fragment.pp
- manifests/init.pp
Maybe this should be fixed by just replacing any non word character instead. Up to you :)
> Neiter ~ or + are allowed in tag names

- lib/puppet/type/concat_fragment.rb
- spec/acceptance/warnings_spec.rb
Prior to this commit, the validation would check for a `Concat_file` with the same **title** as the fragment's **path**. Unfortunately, they're not guaranteed to be the same. The `path` defaults to the `title` but can be passed in by the user.
> (MODULES-3332 ) Correct the path validation.

- lib/puppet/type/concat_fragment.rb
The check should not warn when fragment `target` is based on `concat_file` `name` instead of `path`.
Previous fix only specifically fixed the case:
```
concat_file {'a_file': path => '/some/path'}
concat_fragment {'foo': target => '/some/path'}
```
But it introduced warnings for the case:
```
concat_file {'a_file': path => '/some/path'}
concat_fragment {'foo': target => 'a_file'}
```
> (MODULES-3332) Correct target validation

- manifests/fragment.pp
- manifests/init.pp
- spec/unit/defines/concat_spec.rb
concat doesn't like the @ symbol in file paths.
This fixes this and amends the unit test to check for this.
> Invalid tag fix

- lib/puppet/type/concat_file.rb
The concat_file type defines an autorequire of related fragments which
can unnecessarily lead to dependency cycles.
It's not evident why fragments exactly need to be required as the type
seems to work fine without it.
This commit drops the autorequire that collects fragments in
concat_file to prevent these dependency cycles from happening.
> (MODULES-4474) Drop autorequire of fragments in concat_file

- .rubocop.yml
- lib/puppet/type/concat_file.rb
- lib/puppet/type/concat_fragment.rb
- spec/unit/type/concat_file_spec.rb
This brings in the first 4 backwards-compatible commits of #428
> Four commits

- Gemfile
- manifests/fragment.pp
- manifests/init.pp
- metadata.json
- spec/acceptance/warnings_spec.rb
- spec/unit/defines/concat_fragment_spec.rb
- spec/unit/defines/concat_spec.rb
The data types for validation are using the puppet 4 types with
validate_legacy to check for any legacy types that will be removed on
the next release. This should be a backwards-compatible change except
that it uses puppet 4's data types.
> (MODULES-4264) Update for puppet 4 data types

- spec/unit/defines/concat_fragment_spec.rb
- spec/unit/defines/concat_spec.rb
A couple of examples were expecting the wrong error messages so this was just a matter of correcting those for Puppet 4. Then I found that depending on minor version, Puppet 4 uses different error messages, so these regex matches are pretty liberal but I think they do the trick.
> (maint) fix spec test errors

- README.md
- manifests/fragment.pp
- manifests/init.pp
- spec/unit/defines/concat_fragment_spec.rb
- spec/unit/defines/concat_spec.rb
As part of the 4.0.0 release of this module, the deprecation warnings for the new data types, as well as the compatibility types, have been removed from all manifests. Also, the README is updated for Puppet 4 types.
> (FM-6154 MODULES-4739) remove deprecation warnings and update README

- spec/acceptance/replace_spec.rb
This commit adds optional quotes to the regexps of the replace_spec that
tests expected change messages.
> (MODULES-5085) Ensure that replace test handles qoutes in change message

- CHANGELOG.md
- metadata.json
This includes updates to the changelog and the metadata.json version in
preparation for a release.
> Release prep for concat 4.0.1

- manifests/fragment.pp
Warning: This method is deprecated, please use match expressions with Stdlib::Compat::String instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["concat/manifests/fragment.pp", 18]:
==> myserver.local:    (stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')
> is_string is deprecated. Please use puppet language

- spec/defines/concat_fragment_spec.rb
- spec/defines/concat_spec.rb
When defines are in spec/defines then rspec-puppet automatically includes the define checks according to https://github.com/rodjek/rspec-puppet/blob/3c16670252f3cf309037f1e0cd3fa71f903bef68/lib/rspec-puppet/example.rb#L22
> Move tests to follow the rpsec-puppet pattern

- metadata.json
Should there be a discussion first if you want to support Debain Stretch?
In any way, Stretch is the new stable for Debian and I dont see any reason not to support it.
We run and tested it on Debian Stretch and we haven't found any issue as of yet.
> Added Debian Stretch (9) to the supported list

- metadata.json
Removing SLES 10, Windows 2003 R2 and OSX 10.9.
Adding OSX 10.10 and 10.11.
These changes are to reflect https://puppet.com/docs/pe/2017.3/installing/supported_operating_systems.html.
> Updating metadata.json

- .sync.yml
Previously in commit b56360e95dfa19ebfa24b5dd1035fdfe0c8b97c6 the sync.yml was
updated to include rubocop testing, however the yml was invalid due to missing
whitespace.  This caused the modulesync_configs testing to fail.  This commit
fixes the whitespace.
[skip ci]
> (maint) Fix typo in sync.yml

- lib/puppet/type/concat_file.rb
Ensure that the source parameter is an array in the error message so that join
works.
> Handle concat_file source when not an array

- lib/puppet/type/concat_file.rb
In Puppet 6, PUP-7141 changed the 3x runtime to stop duplicating
strings. Providers will now usually receive frozen strings. Update the
concat_file provider to create a new copy of a string if it needs to add
to it rather than attempt to mutate the original.
> (MODULES-7790) Fix modifying frozen string literal

- lib/puppet/type/concat_file.rb
Reverts puppetlabs/puppetlabs-concat#521
The change that caused this in Puppet was reverted in https://github.com/puppetlabs/puppet/commit/16963e37d4e06564981725f8b87d836f715a42dc and https://github.com/puppetlabs/puppet/pull/7073.
> Revert "(MODULES-7790) Fix modifying frozen string literal"

- lib/puppet/type/concat_file.rb
- spec/acceptance/newline_spec.rb
Prior to this commit, ensure_newline used '\n' everywhere.
With this commit, ensure_newline uses '\r\n' on Windows.
> (MODULES-7717) ensure_newline uses unix line ending on windows

- spec/acceptance/newline_spec.rb
Fix `ensure_newline` acceptance test for windows2012r2-64default.a
> (MODULES-8088) - newline_spec.rb test expectation update

- metadata.json
Changing windows OS support names to match the rest of our supported modules.
> (maint) - Normalise Windows OS Names

- lib/puppet/type/concat_file.rb
- spec/acceptance/format_spec.rb
When using a concat file of format yaml, if a user attempts to pass in yaml arrays as the content, an error is thrown. This fix rectifies this and adds an additional test to verify the changes.
> (MODULES-8287) - Fix fomat=>'yaml' allowing only hashes

- lib/puppet/type/concat_file.rb
- spec/acceptance/force_spec.rb
Fix regression in behavior introduced in the 5.2.0 release
with the fix for MODULES-8287. Restore the behavior where arrays
nested inside hashes will be merged.
> (MODULES-9479) Fix nested array merge behavior

- .rubocop.yml
- .sync.yml
- .travis.yml
- Rakefile
- metadata.json
- spec/default_facts.yml
Previously the module unmanaged the Travis CI file when converted to Litmus.
This commit allows the Travis CI file to be managed.
> (PDK-1501) Allow Travis CI config to be templated

- Gemfile
- metadata.json
This PR is the result of a `pdk update` to ensure that [this change](https://github.com/puppetlabs/puppetlabs-mysql/commit/0813f47bf8709526697d2cd88c0a99301f6666a3) is reverted and the module points to the latest released version of `pdk` now.
> PDK Update to remove PDK-1525 workaround

- lib/puppet/type/concat_file.rb
`$` matches both end of string and end of line.
so `/\n$/` matches `\n\n` anywhere in the string.
while `/\n\Z/` only matches `\n` at the end of the string.
```
irb(main):021:0> "a\n\nb" =~ /\n$/
=> 1
irb(main):022:0> "a\n\nb" =~ /\n\Z/
=> nil
irb(main):023:0> "a\n\nb\n" =~ /\n$/
=> 1
irb(main):024:0> "a\n\nb\n" =~ /\n\Z/
=> 4
```
> Fix newline handling at the end of fragments

- REFERENCE.md
- manifests/fragment.pp
- spec/defines/concat_fragment_spec.rb
This allows the `content` parameter of `concat::fragment` to be an `Deferred` function.
> Add support for Deferred function in concat fragment

- lib/puppet/type/concat_file.rb
- spec/acceptance/concat_spec.rb
When no concat_fragment resources are specified, concat_file
should manage an empty file. This resolves MODULES-9711 and
MODULES-7371.
> (MODULES-9711) Consistently manage concat with no fragments

- lib/puppet/type/concat_file.rb
Apparently it can be the case that one of the hashes is nil. I added a nil check in the merge function.
```
Error: /Stage[main]/xxx::Config/Concat[/etc/file/config.yml]/Concat_file[/etc/file/config.yml]: Failed to generate additional resources us
ing 'eval_generate': undefined method `empty?' for nil:NilClass
/opt/puppetlabs/puppet/cache/lib/puppet/type/concat_file.rb:266:in `nested_merge'
/opt/puppetlabs/puppet/cache/lib/puppet/type/concat_file.rb:232:in `block in should_content'
/opt/puppetlabs/puppet/cache/lib/puppet/type/concat_file.rb:231:in `each'
/opt/puppetlabs/puppet/cache/lib/puppet/type/concat_file.rb:231:in `reduce'
/opt/puppetlabs/puppet/cache/lib/puppet/type/concat_file.rb:231:in `should_content'
/opt/puppetlabs/puppet/cache/lib/puppet/type/concat_file.rb:355:in …
```
> fix merge nil hashes

- lib/puppet/type/concat_file.rb
This can have unexpected side effects and break other code that relies on it. This takes a safer approach by iterating over it.
Fixes: dd88b1a4eee853cfff60b99096c05ce85a9d556e
> Do not modify metaparams in place

- spec/spec_helper_acceptance_local.rb
We are currently seeing transient errors where tests are executed but the setup hasn't happened which then causes failures. This will enable us to debug easier and fail at the correct point in time. Also it will avoid tests executing before the files are created because it needs the LitmusHelper execution to complete before it can evaluate if there have been failures or not.
> (maint) harden test setup

- metadata.json
(GH-iac-334) Remove Support for Ubuntu 14.04
pdk version: `2.1.0`
> pdksync - (GH-iac-334) Remove Support for Ubuntu 14.04

- metadata.json
Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
In this commit:
- Support for Solaris 10 was dropped.
- Support for Windows 7 and 8.1 was dropped.
- Support for Windows Server 2008 R2 was dropped.
- Support for AIX 5.3 and 6.1 was dropped.
The list of supported OSs can be found here:
https://puppet.com/docs/pe/2021.7/supported_operating_systems.html
> (MAINT) Drop support for Solaris 10, Windows (7, 8.1), Windows Server 2008 R2 and AIX (5.3, 6.1)

- .sync.yml
Versions above 1.15.2 seem to suffer from a dependency chain issue where the async gem implicitly sets the minimum supported ruby version to 3.0.
This change ensures that we pin to 1.15.2 in the .sync.yaml.
> (CONT-422) - Pin changelog generator

- lib/puppet/type/concat_file.rb
Prior to this commit, there was an issue regarding the loading of the puppet/type/file/owner constant under certain circumstances during agent runs.
This commit aims to modernise the file request to comply with best practices.
> (MODULES-3522) Removing redundant 'requires'

- lib/puppet/type/concat_file.rb
As established in #758, this update caused an unexpected regression. Reverts puppetlabs/puppetlabs-concat#755
> Revert "(MODULES-3522) Removing redundant 'requires'"

- manifests/fragment.pp
puppet 5 support was dropped sometime ago.  This PR simply removes some old code which was around to support puppet5's lack of deferred functions
> puppet5: drop remnants of puppet5 code

- REFERENCE.md
- lib/puppet/type/concat_file.rb
- manifests/init.pp
- spec/acceptance/concat_spec.rb
- spec/unit/type/concat_file_spec.rb
By default concat would always create an empty file if no fragment was defined. Sometimes we don't want a file unless it has content.
> Add parameter to not create empty files when no fragments are defined

- CHANGELOG.md
Prior to this commit, it was brought to light an error in PR naming for Puppet 8 support related PRs, where they failed to mention the potential drop in Puppet 6 support. This commit aims to fix the changelog so that it reflects better the changes made in this major update.
> (CONT-874) Update changelog to address wrong title

- lib/puppet/type/concat_fragment.rb
This reverts commit bc6478ae57ac25be6a53c8c64eca179853c3a598.
The API is `sensitive_parameters`, we can't just change the name of this method in this type because rubocop complains.
> Revert "Correct Naming/AccessorMethodName"

- metadata.json
- spec/acceptance/format_spec.rb
(MAINT) - Update Stdlib dependency
pdk version: `2.7.1`
> pdksync - (MAINT) - Allow Stdlib 9.x

- lib/puppet/type/concat_file.rb
Changes introduced as part of https://github.com/puppetlabs/puppetlabs-concat/pull/789 causing regression with puppet 7.14.
https://github.com/puppetlabs/puppetlabs-concat/issues/803
> (CAT-1692) - Compatibility fix with puppet 7.14

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
Reinstate ubuntu-20.04 as the github actions runner image. 
This is done because Centos-7, OracleLinux-7 and Scientific-7 are not getting provisioned on the ubuntu-2204 github runner image resulting in nightly job failures: https://github.com/puppetlabs/puppetlabs-concat/actions/runs/11395101272. It might be due to the EOL status of EL-7.
> Reinstate ubuntu-20.04 as the github action runner image
