- spec/unit/classes/concat_setup_spec.rb
- spec/unit/defines/concat_fragment_spec.rb
- spec/unit/defines/concat_spec.rb
> Fix pending tests

- CHANGELOG.md
- metadata.json
https://tickets.puppetlabs.com/browse/FM-2477
> Updates CHANGELOG and metadata for 1.2.1 release

- .fixtures.yml
- manifests/fragment.pp
- manifests/init.pp
- metadata.json
- spec/spec_helper_acceptance.rb
Requires https://github.com/electrical/puppet-lib-file_concat/pull/26
> Fixes windows

- README.md
See discussion in
https://github.com/puppetlabs/puppetlabs-concat/pull/320/files#r31339621
> Fixup the wording in README

- manifests/fragment.pp
- manifests/init.pp
- spec/acceptance/concat_spec.rb
(MODULES-2094) Adds acceptance tests for special characters
Added an acceptance test for checking special characters.
Closes #327
> (MODULES-2094) Extend regexp to remove parenthesis on safe names

- manifests/fragment.pp
- manifests/init.pp
- spec/unit/defines/concat_fragment_spec.rb
- spec/unit/defines/concat_spec.rb
Reverts puppetlabs/puppetlabs-concat#359
> Revert "Backup option breaks concat"

- lib/puppet/type/concat_file.rb
as described in
https://tickets.puppetlabs.com/browse/MODULES-3097
> (MODULES-3097) fix fragment sorting

- spec/spec_helper_acceptance.rb
> This is wrong.

- README.md
Updates to reflect changes from #397
> (maint) Updates README to reflect new fragment target description.

- lib/puppet/type/concat_file.rb
> Keep the whole fragment title to sort

- manifests/fragment.pp
- spec/unit/defines/concat_fragment_spec.rb
Also made error messages more consistent and updated relevant spec test.
> [#puppethack] MODULES-3900 add resource info to error messages

- Gemfile
a comment
https://github.com/puppetlabs/modulesync_configs/pull/114
https://github.com/puppetlabs/modulesync_configs/pull/112
> (FM-5972) gettext and spec.opts

- .sync.yml
We want to add appveyor for the concat module so first we have to
update the .sync.yml file to add the appveyor configuration.
> (MODULES-4517) Update modulesync configs for appveyor

- metadata.json
Updating the metadata.json to contain up to date Windows Operating Systems list.
> (MODULES-5884) -  Updating Windows OS

- .gitignore
- .pdkignore
- .rubocop.yml
- .travis.yml
- Gemfile
- README.md
- Rakefile
- metadata.json
- spec/spec_helper.rb
pdk update ran as there were bundler failures in Travis. Running this consumed latest templates with fix.
> (MODULES-7620) - Update README Limitations section

- README.md
- lib/puppet/type/concat_file.rb
- manifests/init.pp
- spec/acceptance/format_spec.rb
- spec/unit/type/concat_file_spec.rb
Hi.
I'm working on a module and I need to concat multiple hashes into a JSON array.
I tried to do my best to implement this in concat, but I'm not really a Ruby guy, so I'm not sure this is the correct way to do so.
> (MODULES-5124) Add support for JSON arrays

- .pdkignore
- .travis.yml
- metadata.json
pdksync_heads/master-0-gbf720df
pdk version: `1.8.0`
> pdksync - pdksync_heads/master-0-gbf720df

- README.md
> (maint) moved the period outside of the link.

- .travis.yml
- metadata.json
- spec/acceptance/locales_spec.rb
pdksync_heads/master-0-g9c815ea
pdk version: `1.7.1` 
This PR also includes test updates to locales_spec as we now have Japanese translations.
> pdksync - pdksync_heads/master-0-g9c815ea

- README.md
I think it's easier to read like this.
> Update README.md to match puppet style guide

- CHANGELOG.md
- metadata.json
> (MODULES-9519) - Release Merge back 6.1.0

- metadata.json
- provision.yaml
> (FM-8698) - Addition of Support for CentOS 8

- .sync.yml
- Gemfile
"(IAC-897) Remove bolt pin from sync.yaml file"
pdk version: `1.18.0`
> pdksync - "(IAC-897) Remove bolt pin from sync.yaml file"

- .devcontainer/devcontainer.json
- .github/workflows/auto_release.yml
- metadata.json
The changes in this PR are as a result of running a PDK update.
Modified files include:
metadata.json
devcontainer.json
auto_release.yml
> (maint) - PDK Update
